// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9jge9vqjVxfeQ0LJW7r5IrlzPkIVqX3A',
    appId: '1:662429319913:web:039c4e0f202b736fdb6678',
    messagingSenderId: '662429319913',
    projectId: 'malisanjay',
    authDomain: 'malisanjay.firebaseapp.com',
    storageBucket: 'malisanjay.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiItQ6JHhb_2ZQS0GSGj5sI7Q-Zw4GK60',
    appId: '1:662429319913:android:a28c3905eb83d9b8db6678',
    messagingSenderId: '662429319913',
    projectId: 'malisanjay',
    storageBucket: 'malisanjay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAzcDyq59Vl8TrnNgo_O9uuahnY8euZC4',
    appId: '1:662429319913:ios:dcb0d39f6d0e690bdb6678',
    messagingSenderId: '662429319913',
    projectId: 'malisanjay',
    storageBucket: 'malisanjay.firebasestorage.app',
    iosBundleId: 'com.example.devPortfolioSanjaymali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAzcDyq59Vl8TrnNgo_O9uuahnY8euZC4',
    appId: '1:662429319913:ios:dcb0d39f6d0e690bdb6678',
    messagingSenderId: '662429319913',
    projectId: 'malisanjay',
    storageBucket: 'malisanjay.firebasestorage.app',
    iosBundleId: 'com.example.devPortfolioSanjaymali',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9jge9vqjVxfeQ0LJW7r5IrlzPkIVqX3A',
    appId: '1:662429319913:web:44dc341eec31d100db6678',
    messagingSenderId: '662429319913',
    projectId: 'malisanjay',
    authDomain: 'malisanjay.firebaseapp.com',
    storageBucket: 'malisanjay.firebasestorage.app',
  );
}
